apiVersion: v1
kind: Pod
metadata:
  name: python-alpine-pod
spec:
  containers:
  - name: python-container
    image: python:3.11-alpine
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
