apiVersion: ray.io/v1
kind: RayService
metadata:
  name: stress-test-serve
spec:
  upgradeStrategy:
    type: NewClusterWithIncrementalUpgrade
    clusterUpgradeOptions:
      gatewayClassName: istio
      stepSizePercent: 10
      intervalSeconds: 30
      maxSurgePercent: 20
  serveConfigV2: |
    applications:
      - name: stress_test_app
        import_path: stress_test_serve.app
        route_prefix: /
        runtime_env:
          working_dir: "https://github.com/future-outlier/ray-serve-load-test/archive/main.zip"
        deployments:
          - name: SimpleDeployment
            autoscaling_config:
              min_replicas: 1
              max_replicas: 2
              target_ongoing_requests: 500
              max_ongoing_requests: 1000
              metrics_interval_s: 0.1      
              upscale_delay_s: 0.5
              downscale_delay_s: 3
            ray_actor_options:
              num_cpus: 1
  rayClusterConfig:
    rayVersion: "2.45.0"
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.45.0
              resources:
                requests:
                  cpu: "2"
                  memory: "2Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - groupName: small-group
        replicas: 1
        minReplicas: 0
        maxReplicas: 4
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:2.45.0
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  requests:
                    cpu: "2"
                    memory: "2Gi"