apiVersion: ray.io/v1
kind: RayService
metadata:
  name: stress-test-serve
spec:
  upgradeStrategy:
    type: NewClusterWithIncrementalUpgrade
    clusterUpgradeOptions:
      gatewayClassName: istio
      stepSizePercent: 10
      intervalSeconds: 30
      maxSurgePercent: 20
  serveConfigV2: |
    applications:
      - name: stress_test_app
        import_path: stress_test_serve:app
        route_prefix: /test
        runtime_env:
          working_dir: "https://github.com/future-outlier/ray-serve-load-test/archive/main.zip"
        deployments:
          - name: SimpleDeployment
            num_replicas: 1
            ray_actor_options:
              num_cpus: 0.5
  rayClusterConfig:
    rayVersion: "2.49.2"
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.49.2
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - groupName: small-group
        replicas: 1
        minReplicas: 0
        maxReplicas: 4
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:2.49.2
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  requests:
                    cpu: "1"
                    memory: "1Gi"

